#!/usr/bin/env python3
"""Record Step 15B RED/GREEN results without manufacturing an oracle."""

from __future__ import annotations

import argparse, csv, hashlib
from collections import Counter
from pathlib import Path

FIELDS=("test_id","requirement_id","defect_id","test_layer","status","expected","actual","difference","evidence_path")

def read(path: Path):
    with path.open(encoding="utf-8-sig",newline="") as h: return list(csv.DictReader(h))

def expected(root: Path,test_id: str) -> str:
    return ";".join(f"{r['field']}={r['expected_value']}" for r in read(root/f"tests/tick_shock/expected/{test_id}_expected.csv"))

def main() -> int:
    ap=argparse.ArgumentParser(); ap.add_argument("--phase",choices=("red","green"),required=True); ap.add_argument("--raw",type=Path); ap.add_argument("--compile-log",type=Path); args=ap.parse_args()
    root=Path(__file__).resolve().parents[2]
    cases=[r for r in read(root/"tests/tick_shock/spec/test_cases.csv") if r["test_id"].startswith("TS15B-")]
    raw={r["test_id"]:r for r in read(args.raw)} if args.raw and args.raw.exists() else {}
    out=root/f"reports/tests/tick_shock/step15b_{args.phase}"
    out.mkdir(parents=True,exist_ok=True)
    rows=[]
    for case in cases:
        tid=case["test_id"]; exp=expected(root,tid)
        if args.phase=="red":
            if tid=="TS15B-DIR-SCHEMA-001":
                header=(root/"reports/backtest/runs/20260827_ts15a_tail_v1_raw_realizable_202503_r2/detector_features.csv").open(encoding="utf-8-sig").readline().strip().split(",")
                actual="direction_column="+("present" if "direction" in header else "missing")
                status="XPASS" if "direction" in header else "XFAIL"
                evidence="reports/backtest/runs/20260827_ts15a_tail_v1_raw_realizable_202503_r2/detector_features.csv"
            else:
                status="XFAIL"; actual="PRODUCTION_CONTROL_FUNNEL_API_ABSENT"; evidence=str(args.compile_log or "reports/compile/tick_shock/step15b_red_ControlFunnel.log")
            difference=f"expected {exp}; actual {actual}"
        else:
            obs=raw.get(tid)
            if obs is None: status="FAIL"; actual="NO_OBSERVATION"; difference="missing production-path result"
            else: status="PASS" if obs.get("observed")=="MATCH" else "FAIL"; actual=obs.get("actual",""); difference=obs.get("difference","")
            evidence=str(args.raw)
        rows.append({"test_id":tid,"requirement_id":case["requirement_id"],"defect_id":case["defect_id"],"test_layer":case["test_layer"],"status":status,"expected":exp,"actual":actual,"difference":difference,"evidence_path":evidence})
    path=out/f"step15b_{args.phase}_results.csv"
    with path.open("w",encoding="utf-8",newline="") as h: w=csv.DictWriter(h,fieldnames=FIELDS); w.writeheader(); w.writerows(rows)
    c=Counter(r["status"] for r in rows)
    report=out/f"step15b_{args.phase}_report.md"
    report.write_text("# Step 15B "+args.phase.upper()+" evidence\n\n"+"\n".join(f"- {k}: {c[k]}" for k in ("PASS","FAIL","XFAIL","XPASS","SKIP","BLOCKED"))+"\n\nExpected values are frozen in the per-Test-ID CSVs and were not generated by production code.\n",encoding="utf-8")
    print(" ".join(f"{k}={c[k]}" for k in ("PASS","FAIL","XFAIL","XPASS","SKIP","BLOCKED")))
    return 0 if args.phase=="red" or (c["FAIL"]==c["XFAIL"]==c["XPASS"]==c["BLOCKED"]==0) else 1

if __name__=="__main__": raise SystemExit(main())

